-- MySQL Script generated by MySQL Workbench
-- Sun 04 Jan 2026 08:23:30 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_teachers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_teachers` (
  `t_id` CHAR(5) NOT NULL,
  `t_name` VARCHAR(45) NOT NULL,
  `t_firstname` VARCHAR(45) NOT NULL,
  `t_birthdate` DATE NULL,
  `t_salary` DECIMAL(10) NULL,
  `t_t_boss` CHAR(5) NOT NULL,
  PRIMARY KEY (`t_id`),
  INDEX `fk_t_teachers_t_teachers_idx` (`t_t_boss` ASC) VISIBLE,
  CONSTRAINT `fk_t_teachers_t_teachers`
    FOREIGN KEY (`t_t_boss`)
    REFERENCES `mydb`.`t_teachers` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`c_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`c_classes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`c_classes` (
  `c_id` VARCHAR(6) NOT NULL,
  `c_text` VARCHAR(45) NULL,
  `c_t_classteacher` CHAR(5) NOT NULL,
  `c_p_classrepsubst` INT NOT NULL,
  `c_p_classrep` INT NOT NULL,
  PRIMARY KEY (`c_id`),
  INDEX `fk_c_class_t_teachers1_idx` (`c_t_classteacher` ASC) VISIBLE,
  INDEX `fk_c_class_p_pupils2_idx` (`c_p_classrepsubst` ASC) VISIBLE,
  INDEX `fk_c_class_p_pupils1_idx` (`c_p_classrep` ASC) VISIBLE,
  UNIQUE INDEX `c_p_classrep_UNIQUE` (`c_p_classrep` ASC) VISIBLE,
  UNIQUE INDEX `c_p_classrepsubst_UNIQUE` (`c_p_classrepsubst` ASC) VISIBLE,
  CONSTRAINT `fk_c_class_t_teachers1`
    FOREIGN KEY (`c_t_classteacher`)
    REFERENCES `mydb`.`t_teachers` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_c_class_p_pupils2`
    FOREIGN KEY (`c_p_classrepsubst`)
    REFERENCES `mydb`.`p_pupils` (`p_pupilnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_c_class_p_pupils1`
    FOREIGN KEY (`c_p_classrep`)
    REFERENCES `mydb`.`p_pupils` (`p_pupilnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`p_pupils`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`p_pupils` ;

CREATE TABLE IF NOT EXISTS `mydb`.`p_pupils` (
  `p_pupilnr` INT NOT NULL,
  `p_name` VARCHAR(45) NOT NULL,
  `p_firstname` VARCHAR(45) NOT NULL,
  `p_birthdate` DATE NOT NULL,
  `p_address` VARCHAR(45) NULL,
  `p_c_class` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`p_pupilnr`),
  INDEX `fk_p_pupils_c_class1_idx` (`p_c_class` ASC) VISIBLE,
  CONSTRAINT `fk_p_pupils_c_class1`
    FOREIGN KEY (`p_c_class`)
    REFERENCES `mydb`.`c_classes` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`r_rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`r_rooms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`r_rooms` (
  `r_id` VARCHAR(6) NOT NULL,
  `r_seats` INT NOT NULL,
  PRIMARY KEY (`r_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`s_subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`s_subjects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`s_subjects` (
  `s_id` INT NOT NULL,
  `s_text` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`s_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`e_exams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`e_exams` ;

CREATE TABLE IF NOT EXISTS `mydb`.`e_exams` (
  `e_date` DATE NOT NULL,
  `e_p_cand` INT NOT NULL,
  `e_s_subject` INT NOT NULL,
  `e_t_teacher` CHAR(5) NOT NULL,
  `e_type` ENUM('WP', 'FP') NOT NULL,
  `e_mark` INT NULL,
  PRIMARY KEY (`e_date`, `e_p_cand`, `e_s_subject`),
  INDEX `fk_e_exams_s_subjects1_idx` (`e_s_subject` ASC) VISIBLE,
  INDEX `fk_e_exams_p_pupils1_idx` (`e_p_cand` ASC) VISIBLE,
  INDEX `fk_e_exams_t_teachers1_idx` (`e_t_teacher` ASC) VISIBLE,
  CONSTRAINT `fk_e_exams_s_subjects1`
    FOREIGN KEY (`e_s_subject`)
    REFERENCES `mydb`.`s_subjects` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_e_exams_p_pupils1`
    FOREIGN KEY (`e_p_cand`)
    REFERENCES `mydb`.`p_pupils` (`p_pupilnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_e_exams_t_teachers1`
    FOREIGN KEY (`e_t_teacher`)
    REFERENCES `mydb`.`t_teachers` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`b_bosses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`b_bosses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`b_bosses` (
  `b_t_subordinate` CHAR(5) NOT NULL,
  `b_type` VARCHAR(45) NOT NULL,
  `b_t_boss` CHAR(5) NOT NULL,
  INDEX `fk_b_bosses_t_teachers1_idx` (`b_t_boss` ASC) VISIBLE,
  INDEX `fk_b_bosses_t_teachers2_idx` (`b_t_subordinate` ASC) VISIBLE,
  PRIMARY KEY (`b_t_subordinate`, `b_type`),
  CONSTRAINT `fk_b_bosses_t_teachers1`
    FOREIGN KEY (`b_t_boss`)
    REFERENCES `mydb`.`t_teachers` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_b_bosses_t_teachers2`
    FOREIGN KEY (`b_t_subordinate`)
    REFERENCES `mydb`.`t_teachers` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`l_lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`l_lessons` ;

CREATE TABLE IF NOT EXISTS `mydb`.`l_lessons` (
  `l_c_class` VARCHAR(6) NOT NULL,
  `l_hour` VARCHAR(4) NOT NULL,
  `l_s_subject` INT NOT NULL,
  `l_t_teacher` CHAR(5) NOT NULL,
  `l_r_room` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`l_c_class`, `l_hour`, `l_s_subject`),
  INDEX `fk_l_lessons_r_rooms1_idx` (`l_r_room` ASC) VISIBLE,
  INDEX `fk_l_lessons_s_subjects1_idx` (`l_s_subject` ASC) VISIBLE,
  INDEX `fk_l_lessons_t_teachers1_idx` (`l_t_teacher` ASC) VISIBLE,
  INDEX `fk_l_lessons_c_class1_idx` (`l_c_class` ASC) VISIBLE,
  CONSTRAINT `fk_l_lessons_r_rooms1`
    FOREIGN KEY (`l_r_room`)
    REFERENCES `mydb`.`r_rooms` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_l_lessons_s_subjects1`
    FOREIGN KEY (`l_s_subject`)
    REFERENCES `mydb`.`s_subjects` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_l_lessons_t_teachers1`
    FOREIGN KEY (`l_t_teacher`)
    REFERENCES `mydb`.`t_teachers` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_l_lessons_c_class1`
    FOREIGN KEY (`l_c_class`)
    REFERENCES `mydb`.`c_classes` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
